# Generated by Django 3.2.7 on 2021-09-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0003_auto_20210908_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcourses',
            old_name='started_from',
            new_name='startedfrom',
        ),
    ]
