# Generated by Django 3.2.7 on 2021-09-08 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0006_remove_allcourses_startedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 19, 7, 49, 933863, tzinfo=utc), verbose_name='Started from'),
            preserve_default=False,
        ),
    ]
