# Generated by Django 3.2.7 on 2021-09-09 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0009_remove_post_date_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
