# Generated by Django 3.2.7 on 2021-09-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0010_post_date_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcourses',
            name='insname',
        ),
    ]
