# Generated by Django 3.2.7 on 2021-09-10 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0011_remove_allcourses_insname'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='insname',
            field=models.CharField(default=datetime.datetime(2021, 9, 10, 12, 20, 11, 48302, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
