# Generated by Django 3.2.7 on 2021-09-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0013_register_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_user',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
