# Generated by Django 3.2.7 on 2021-09-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0014_auto_20210914_1658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Login',
        ),
    ]
